version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: job_queue_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: job_queue
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: job_queue_redis
    ports:
      - "6379:6379"
    restart: unless-stopped

  api:
    build: .
    command: npm run start -w apps/api
    environment:
      DATABASE_URL: postgres://postgres:password@postgres:5432/job_queue
      REDIS_URL: redis://redis:6379
      PORT: 3000
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - redis

  worker:
    build: .
    command: npm run start -w apps/worker
    environment:
      DATABASE_URL: postgres://postgres:password@postgres:5432/job_queue
      WORKER_QUEUE_NAME: email_notifications
      WORKER_CONCURRENCY: 5
    depends_on:
      - postgres
    deploy:
      replicas: 3

volumes:
  pgdata: